import SiteShell from './SiteShell';
import PageHero from './PageHero';
import { values } from '../content/site';

export default function AboutPage({ lang='id' }) {
  const id = lang === 'id';
  return <SiteShell lang={lang}>
    <PageHero index="01" kicker={id ? 'TENTANG MBPI' : 'ABOUT MBPI'} title={id ? 'Bergerak bersama rantai pasok Indonesia sejak 1993.' : 'Moving with Indonesia supply chain since 1993.'} intro={id ? 'MBPI adalah inland container terminal yang menangani penyimpanan, transit, warehousing, dan aktivitas terkait kontainer melalui tenaga profesional dan sistem terkomputerisasi.' : 'MBPI is an inland container terminal supporting storage, transit, warehousing, and container-related operations with qualified personnel and computerized management.'}/>
    <section className="section"><div className="container aboutStatement"><div><span className="sectionIndex">01A</span><h2>{id ? 'Perusahaan kami' : 'Our company'}</h2></div><div><p>{id ? 'Kami melayani carrier, container leasing company, dan kebutuhan logistik lain dengan pendekatan one-stop service. Fokus kami adalah memberikan operasi yang aman, konsisten, dan mudah diakses oleh partner bisnis.' : 'We serve carriers, container leasing companies, and broader logistics requirements through a one-stop service model focused on safe, consistent, and accessible operations.'}</p><div className="tagRow"><span>{id ? 'Perusahaan Multinasional' : 'Multinational Company'}</span><span>{id ? 'Pelayanan Prima' : 'Service Excellence'}</span><span>{id ? 'Kepuasan Pelanggan' : 'Customer Satisfaction'}</span><span>{id ? 'Berorientasi Keselamatan' : 'Safety Oriented'}</span></div></div></div></section>
    <section className="section valuesBand"><div className="container"><div className="sectionHead compact"><div><span className="sectionIndex">02</span><span className="kicker">{id ? 'NILAI INTI' : 'CORE VALUES'}</span></div><h2>{id ? 'Prinsip yang menjaga kualitas operasi.' : 'Principles that protect operational quality.'}</h2></div><div className="valueGrid">{values.map((v,i)=><article key={v}><span>0{i+1}</span><h3>{v}</h3></article>)}</div></div></section>
    <section className="section darkBand"><div className="container missionGrid"><div><div className="kicker lightKicker">{id ? 'VISI' : 'VISION'}</div><h2>{id ? 'Menjadi partner bernilai melalui layanan logistik satu atap.' : 'To be a valuable partner through one-stop logistics services.'}</h2></div><div><div className="kicker lightKicker">{id ? 'MISI' : 'MISSION'}</div><p>{id ? 'Memberikan kemudahan bagi mitra melalui layanan terintegrasi, personel berkualifikasi, dan fasilitas berstandar tinggi.' : 'Bring convenience to partners through integrated services, qualified personnel, and high-standard facilities.'}</p></div></div></section>
  </SiteShell>;
}
